export const CATEGORIES = [
  "Animations",
  "Backgrounds",
  "Buttons",
  "Cards",
  "Checkboxes",
  "Cursors",
  "Forms",
  "Glassmorphism",
  "Gradients",
  "Hover Effects",
  "Inputs",
  "Layouts",
  "Loaders",
  "Navigation",
  "Neumorphism",
  "Responsive",
  "Shapes",
  "Switches",
  "Text Effects",
  "Transforms",
  "Typography",
  "UI Components"
];
